//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HalfChessClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public Nullable<int> game_id { get; set; }
        public string player_name { get; set; }
        public Nullable<int> player_id { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<int> think_time { get; set; }
        public Nullable<bool> finshed { get; set; }
        public Nullable<bool> win { get; set; }
        public Nullable<int> finish_reason { get; set; }
    }
}
